### ISSUE TITLE
[Installation] NotImplementedError

### ISSUE THREAD

**Issue by sdan** [arex18/rocket-lander#3]
When I ran 
``` python main_simulation.py ```

I'm getting this weird NotImplementedError. Do I need to manually edit the core.py file to implement this?

Here's the error:

```
gym/gym/__init__.py:22: UserWarning: DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.
  warnings.warn('DEPRECATION WARNING: to improve load times, gym no longer automatically loads gym.spaces. Please run "import gym.spaces" to load gym.spaces on your own. This warning will turn into an error in a future version of gym.')
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Traceback (most recent call last):
  File "main_simulation.py", line 19, in <module>
    env = RocketLander(settings)
  File "/Users/surya/Downloads/rocket-lander/environments/rocketlander.py", line 86, in __init__
    self.reset()
  File "/Users/surya/Documents/gym/gym/core.py", line 70, in reset
    raise NotImplementedError
NotImplementedError
```

**Comment by arex18** [comment]
What gym version are you using? Try `pip install --force-reinstall gym==0.9.4`.

**Comment by sdan** [comment]
Interesting, but quite strange solution (I had version 0.10.9 installed).
Nevertheless, this helped me solve the problem.
👍
